Repository AlexAlonRo/Invasion-Canina, pull requests merged in 2023-11, with the labels that each got.

#7 Efectos de Sonido
  Sonidos/Sonido Extintor.m4a
  Sonidos/Sonido Gruñido de perro.m4a
  Sonidos/Sonido Palos.m4a
  Sonidos/Sonido Pistola de clavos.m4a
Labels: Cambios

#8 Enemigos v1
  Recursos del Juego/Enemigos/perro.aseprite
  Recursos del Juego/Enemigos/perro2.aseprite
  Recursos del Juego/Enemigos/perro3.aseprite
Labels: Cambios

#9 Escenarios y Niveles v1
  Recursos del Juego/Escenarios/escenario01.png
  Recursos del Juego/Escenarios/escenario1.aseprite
  Recursos del Juego/Escenarios/escenario1.png
  Recursos del Juego/Escenarios/escenario2.aseprite
  Recursos del Juego/Escenarios/escenario2.png
  Recursos del Juego/Escenarios/escenario3.aseprite
  Recursos del Juego/Escenarios/escenario3.png
  Recursos del Juego/Niveles/2.jpeg
  Recursos del Juego/Niveles/3.jpeg
  Recursos del Juego/Niveles/main menu.jpeg
  Recursos del Juego/Niveles/menu principal.jpeg
  Recursos del Juego/Niveles/niveles.jpeg
Labels: Cambios

#10 Música Niveles
  Sonidos/Nivel 1.mp3
  Sonidos/Nivel 2.mp3
  Sonidos/Nivel 3.mp3
Labels: Cambios

#11 Objetos y Armas v1
  Recursos del Juego/Armas y Objetos/armas.aseprite
  Recursos del Juego/Armas y Objetos/armas.png
  Recursos del Juego/Armas y Objetos/botiquin v1.aseprite
  Recursos del Juego/Armas y Objetos/extintor v1.aseprite
  Recursos del Juego/Armas y Objetos/municion v1.aseprite
  Recursos del Juego/Armas y Objetos/objetos.aseprite
  Recursos del Juego/Armas y Objetos/objetos.png
  Recursos del Juego/Armas y Objetos/pistola v1.aseprite
  Recursos del Juego/Armas y Objetos/posion1 v1.aseprite
  Recursos del Juego/Armas y Objetos/posion2 v1.aseprite
  Recursos del Juego/Armas y Objetos/redbull v1.aseprite
Labels: Cambios

#12 Animaciones de Ataque
  Recursos del Juego/Alexander/Alex-Extintor/Alexander Derecho-Extintor Disparando.aseprite
  Recursos del Juego/Alexander/Alex-Extintor/Alexander Dispaando.aseprite
  Recursos del Juego/Alexander/Alex-Extintor/Alexander Disparando.aseprite
  Recursos del Juego/Alexander/Alex-Extintor/Alexander Izquierdo-Extintor Disparando.aseprite
  Recursos del Juego/Alexander/Alex-Palo/Alexander Derecho-Palo Pegando.aseprite
  Recursos del Juego/Alexander/Alex-Palo/Alexander Izquierdo-Palo Pegando.aseprite
  Recursos del Juego/Alexander/Alex-Pistola/Alexander Derecho-Pistola Disparando.aseprite
  Recursos del Juego/Alexander/Alex-Pistola/Alexander Disparando.aseprite
  Recursos del Juego/Alexander/Alex-Pistola/Alexander Izquierdo-Pistola Disparando.aseprite
  Recursos del Juego/Alexander/Alexander Saltar.aseprite
Labels: Cambios

#15 rankingAndCinematicav1
  InvasionCanina2D/Assets/Dialogos.meta
  InvasionCanina2D/Assets/Dialogos/Dialogo1.cs
  InvasionCanina2D/Assets/Dialogos/Dialogo1.cs.meta
  InvasionCanina2D/Assets/Prefabs/row.prefab
  InvasionCanina2D/Assets/Prefabs/row.prefab.meta
  InvasionCanina2D/Assets/Scenes/Cinematica1.unity
  InvasionCanina2D/Assets/Scenes/Cinematica1.unity.meta
  InvasionCanina2D/Assets/Scenes/GameScene_HighscoreTable.unity
  InvasionCanina2D/Assets/Scenes/GameScene_HighscoreTable.unity.meta
  InvasionCanina2D/Assets/Scenes/MenuInicial.unity
  InvasionCanina2D/Assets/Scenes/Nivel1.unity
  InvasionCanina2D/Assets/Scripts/Healt/Damage.cs
  InvasionCanina2D/Assets/Scripts/Healt/Damage.cs.meta
  InvasionCanina2D/Assets/Scripts/Menus/MenuInicial.cs
  InvasionCanina2D/Assets/Scripts/Score.meta
  InvasionCanina2D/Assets/Scripts/Score/RowUi.cs
  InvasionCanina2D/Assets/Scripts/Score/RowUi.cs.meta
  InvasionCanina2D/Assets/Scripts/Score/Score.cs
  InvasionCanina2D/Assets/Scripts/Score/Score.cs.meta
  InvasionCanina2D/Assets/Scripts/Score/ScoreData.cs
  InvasionCanina2D/Assets/Scripts/Score/ScoreData.cs.meta
  InvasionCanina2D/Assets/Scripts/Score/ScoreManager.cs
  InvasionCanina2D/Assets/Scripts/Score/ScoreManager.cs.meta
  InvasionCanina2D/Assets/Scripts/Score/ScoreUi.cs
  InvasionCanina2D/Assets/Scripts/Score/ScoreUi.cs.meta
  InvasionCanina2D/Assets/Sprites/Fondos/Alex.png
  InvasionCanina2D/Assets/Sprites/Fondos/Alex.png.meta
  InvasionCanina2D/Assets/Sprites/Fondos/Border.png
  InvasionCanina2D/Assets/Sprites/Fondos/Border.png.meta
  InvasionCanina2D/Assets/Sprites/Fondos/E-removebg-preview.png
  InvasionCanina2D/Assets/Sprites/Fondos/E-removebg-preview.png.meta
  InvasionCanina2D/Assets/Sprites/Fondos/Omitir.png
  InvasionCanina2D/Assets/Sprites/Fondos/Omitir.png.meta
  InvasionCanina2D/Assets/Sprites/Fondos/R.png
  InvasionCanina2D/Assets/Sprites/Fondos/R.png.meta
  InvasionCanina2D/Assets/Sprites/Fondos/Reglas.png
  InvasionCanina2D/Assets/Sprites/Fondos/Reglas.png.meta
  InvasionCanina2D/Assets/Sprites/Fondos/Tona.png
  InvasionCanina2D/Assets/Sprites/Fondos/Tona.png.meta
  InvasionCanina2D/Assets/Sprites/Fondos/TrophyStar.png
  InvasionCanina2D/Assets/Sprites/Fondos/TrophyStar.png.meta
  InvasionCanina2D/Assets/Sprites/Fondos/Y.png
  InvasionCanina2D/Assets/Sprites/Fondos/Y.png.meta
  InvasionCanina2D/Assets/Sprites/Fondos/teclas-removebg-preview.png
  InvasionCanina2D/Assets/Sprites/Fondos/teclas-removebg-preview.png.meta
  InvasionCanina2D/Assets/Sprites/Materials/PaletteSuelo.prefab
  InvasionCanina2D/Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Bangers SDF.asset
  InvasionCanina2D/ProjectSettings/EditorBuildSettings.asset
Labels: Desarollo, Cambios

#19 Cinematica Nivel 2 y Efectos de Sonido
  InvasionCanina2D/Assets/Audio/Sonido-Disparo.mp3
  InvasionCanina2D/Assets/Audio/Sonido-Disparo.mp3.meta
  InvasionCanina2D/Assets/Audio/Sonido-Extintor.mp3
  InvasionCanina2D/Assets/Audio/Sonido-Extintor.mp3.meta
  InvasionCanina2D/Assets/Audio/Sonido-Gruñido-de-perro.mp3
  InvasionCanina2D/Assets/Audio/Sonido-Gruñido-de-perro.mp3.meta
  InvasionCanina2D/Assets/Audio/Sonido-Palos.mp3
  InvasionCanina2D/Assets/Audio/Sonido-Palos.mp3.meta
  InvasionCanina2D/Assets/Prefabs/Enemigos/PerroMele.prefab
  InvasionCanina2D/Assets/Prefabs/Objetos/Extintor.prefab
  InvasionCanina2D/Assets/Prefabs/Objetos/Palo.prefab
  InvasionCanina2D/Assets/Prefabs/Objetos/Pistola.prefab
  InvasionCanina2D/Assets/Scenes/Cinematica2.unity
  InvasionCanina2D/Assets/Scenes/Cinematica2.unity.meta
  InvasionCanina2D/Assets/Scenes/Nivel1.unity
  InvasionCanina2D/Assets/Scripts/Armas/CQC/CQCWeapon.cs
  InvasionCanina2D/Assets/Scripts/Armas/Gun/ProjectileGunWeapon.cs
  InvasionCanina2D/Assets/Scripts/Armas/Gun/TraceGunWeapon.cs
  InvasionCanina2D/Assets/Sprites/Fondos/Fondo_Nivel2.jpg
  InvasionCanina2D/Assets/Sprites/Fondos/Fondo_Nivel2.jpg.meta
  InvasionCanina2D/Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Bangers SDF.asset
Labels: Desarollo, Cambios

#22 nivel2
  InvasionCanina2D/Assets/Scenes/MenuInicial.unity
  InvasionCanina2D/Assets/Scenes/Nivel2.unity
  InvasionCanina2D/ProjectSettings/EditorBuildSettings.asset
  InvasionCanina2D/ProjectSettings/ProjectSettings.asset
  Recursos del Juego/Enemigos/PerraMadre.aseprite
  Recursos del Juego/Enemigos/PerraMadre.png
Labels: Desarollo, Cambios

#23 merge
  InvasionCanina2D/Assets/Dialogos/Dialogo1.cs
  InvasionCanina2D/Assets/Scenes/Cinematica2.unity
  InvasionCanina2D/Assets/Scenes/Nivel1.unity
  InvasionCanina2D/Assets/Scenes/Nivel1T.unity
  InvasionCanina2D/Assets/Scripts/Menus/Menu.cs
  InvasionCanina2D/Assets/Scripts/Menus/MenuInicial.cs
  InvasionCanina2D/ProjectSettings/EditorBuildSettings.asset
Labels: bug
