Repository AlexAlonRo/Invasion-Canina, pull requests merged in 2023-12, with the labels that each got.

#28 Correcciones en Cinematicas y habilidades de Personajes
  InvasionCanina2D/Assets/Audio/CancionFinal.mp3
  InvasionCanina2D/Assets/Audio/CancionFinal.mp3.meta
  InvasionCanina2D/Assets/Audio/Gruñido1.mp3
  InvasionCanina2D/Assets/Audio/Gruñido1.mp3.meta
  InvasionCanina2D/Assets/Audio/Gruñido2.mp3
  InvasionCanina2D/Assets/Audio/Gruñido2.mp3.meta
  InvasionCanina2D/Assets/Prefabs/Enemigos/PerroRocket.prefab
  InvasionCanina2D/Assets/Prefabs/Enemigos/PerroRocket2.prefab
  InvasionCanina2D/Assets/Prefabs/Enemigos/boss.prefab
  InvasionCanina2D/Assets/Scenes/Cinematica2.unity
  InvasionCanina2D/Assets/Scenes/Cinematica3.unity
  InvasionCanina2D/Assets/Scenes/CinematicaFinal.unity
  InvasionCanina2D/Assets/Scenes/MenuInicial.unity
  InvasionCanina2D/Assets/Scenes/Nivel1.unity
  InvasionCanina2D/Assets/Scenes/Nivel1T.unity
  InvasionCanina2D/Assets/Scenes/Nivel2.unity
  InvasionCanina2D/Assets/Scenes/Nivel2T.unity
  InvasionCanina2D/Assets/Scenes/Nivel3.unity
  InvasionCanina2D/Assets/Scenes/Nivel3T.unity
  InvasionCanina2D/Assets/Sprites/Fondos/Habilidades.png
  InvasionCanina2D/Assets/Sprites/Fondos/Habilidades.png.meta
  InvasionCanina2D/Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Bangers SDF.asset
Labels: bug, Cambios

#29 Bugs ranking
  InvasionCanina2D/Assets/Scenes/Cinematica1.unity
  InvasionCanina2D/Assets/Scripts/Menus/ControllerUser.cs
  InvasionCanina2D/Assets/Scripts/Menus/MenuInicial.cs
Labels: bug, Cambios

#30 Cinematicas Final
  InvasionCanina2D/Assets/Prefabs/Enemigos/ExtintorPerro 1.prefab
  InvasionCanina2D/Assets/Prefabs/Enemigos/PerroGun.prefab
  InvasionCanina2D/Assets/Prefabs/Enemigos/PerroRocket2.prefab
  InvasionCanina2D/Assets/Prefabs/Enemigos/boss.prefab
  InvasionCanina2D/Assets/Scenes/Cinematica1.unity
  InvasionCanina2D/Assets/Scenes/Cinematica1.unity.meta
  InvasionCanina2D/Assets/Scenes/Cinematica2.unity
  InvasionCanina2D/Assets/Scenes/Cinematica3.unity
  InvasionCanina2D/Assets/Scenes/CinematicaFinal.unity
  InvasionCanina2D/Assets/Scenes/Nivel1.unity
  InvasionCanina2D/Assets/Scenes/Nivel1T.unity
  InvasionCanina2D/Assets/Scenes/Nivel2.unity
  InvasionCanina2D/Assets/Scenes/Nivel2T.unity
  InvasionCanina2D/Assets/Scenes/Nivel3.unity
  InvasionCanina2D/Assets/Scenes/Nivel3T.unity
Labels: bug, Cambios

#32 Acomodar dimensiones en Movil
  InvasionCanina2D-Movil/Assets/Scenes/Cinematica3.unity
  InvasionCanina2D-Movil/Assets/Scenes/MenuInicial.unity
  InvasionCanina2D-Movil/Assets/Scenes/Nivel1T.unity
  InvasionCanina2D-Movil/Assets/Scenes/Nivel2.unity
  InvasionCanina2D-Movil/Assets/Scenes/Nivel2T.unity
  InvasionCanina2D-Movil/Assets/Scenes/Nivel3.unity
  InvasionCanina2D-Movil/Assets/Scenes/Nivel3T.unity
Labels: Cambios

#33 Aspectos Legales del videojuego
  Aspectos legales del videojuego Saber.pdf
Labels: documentation
